app1/urls.py
from django.urls import path
from . import views

app_name='app1'

urlpatterns = [
    path('',views.index,name='index'),
    path('rutaEjemplo',views.rutaEjemplo,name='rutaEjemplo')
]

app3/urls.py
from django.urls import path
from . import views

app_name='app3'

urlpatterns = [
    path('',views.index,name='index'),
    path('nuevoUsuario',views.nuevoUsuario,name='nuevoUsuario'),
    path('verTareas/<str:idPersona>',views.verTareas,name='verTareas')
]

primerProyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app4.urls')),
    path('app2/',include('app2.urls')),
    path('app3/',include('app3.urls')),
    path('app1/',include('app1.urls')),
]

#127.0.0.1:8000/   app2   / welcome

app3/models.py
from django.db import models

# Create your models here.
class personas(models.Model):
    nombre = models.CharField(max_length=32, null=True, blank=True)
    apellido = models.CharField(max_length=32, null=True, blank=True)
    fecha = models.CharField(max_length=32, null=True, blank=True)
    tipoPersona = models.CharField(max_length=32, null=True, blank=True)
    codigoPersona = models.CharField(max_length=32, null=True, blank=True)

class datosAdicionales(models.Model):
    telefono = models.CharField(max_length=32, null=True, blank=True)
    residencia = models.CharField(max_length=32, null=True, blank=True)
    personaRel = models.OneToOneField(personas, null=True, blank=True, on_delete=models.CASCADE)

class tareasxPersona(models.Model):
    nombre = models.CharField(max_length=32, null=True, blank=True)
    descripcion = models.CharField(max_length=32, null=True, blank=True)
    personaRel= models.ForeignKey(personas,null=True, blank=True, on_delete=models.SET_NULL)

app3/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import personas, datosAdicionales

# Create your views here.
def index(request):
    personasTotales = personas.objects.all()
    return render(request,'index.html',{
        'personasTotales':personasTotales
    })

def nuevoUsuario(request):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        apellido = request.POST.get('apellido')
        fechaNacimiento = request.POST.get('fecha')
        tipoPersona = request.POST.get('tipo')
        codigoPersona = request.POST.get('codigo')
        telefono = request.POST.get('telefono')
        residencia = request.POST.get('residencia')
        
        personaCreada = personas.objects.create(
            nombre=nombre,
            apellido=apellido,
            fecha=fechaNacimiento,
            tipoPersona=tipoPersona,
            codigoPersona=codigoPersona
        )

        datosAdicionales.objects.create(
            telefono=telefono,
            residencia=residencia,
            personaRel=personaCreada
        )

        return HttpResponseRedirect(reverse('app3:index'))
    return render(request,'nuevoUsuario.html')

def verTareas(request,idPersona):
    personaInfo = personas.objects.get(id=idPersona)
    tareasxUsuario = personaInfo.tareasxpersona_set.all()
    return render(request,'verTareas.html',{
        'tareasxUsuario':tareasxUsuario
    })

app3/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Gestor de usuarios</title>
        <style>
            table {
                width: 80%;
                border-collapse: collapse;
            }

            table, th, td {
                border: 1px solid;
            }
        </style>
    </head>
    <body>
        <div style="text-align: center;">
            <h1>VISTA PRINCIPAL - GESTOR DE USUARIOS</h1>
        </div>
        <div style="display: flex; flex-direction: row; justify-content: space-around;">
            <a href="{% url 'app3:nuevoUsuario' %}">
                <button style="width: 120px;">Nuevo usuario</button>
            </a>
            <a>
                <button style="width: 120px;">Ver historico</button>
            </a>
        </div>
        <br>
        <div style="display: flex; flex-direction: row; justify-content: center;">
            <table>
                <thead>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Fecha de nacimiento</th>
                    <th>Tipo de persona</th>
                    <th>Codigo de persona</th>
                    <th>Telefono</th>
                    <th>Residencia</th>
                    <th>Ver tareas</th>
                </thead>
                <tbody>
                    {% for personaInfo in personasTotales %}
                    <tr>
                        <td>{{ personaInfo.nombre }}</td>
                        <td>{{ personaInfo.apellido }}</td>
                        <td>{{ personaInfo.fecha }}</td>
                        <td>{{ personaInfo.tipoPersona }}</td>
                        <td>{{ personaInfo.codigoPersona }}</td>
                        <td>{{ personaInfo.datosadicionales.telefono }}</td>
                        <td>{{ personaInfo.datosadicionales.residencia }}</td>
                        <td><a href="{% url 'app3:verTareas' personaInfo.id %}"><button>Ver</button></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>
</html>

app3/templates/nuevoUsuario.html
<!DOCTYPE html>
<html>
    <head>
        <title>Nuevo usuario</title>
    </head>
    <body>
        <div style="text-align: center;">
            <h1>CREAR NUEVO USUARIO</h1>
        </div>
        <br>
        <div>
            <a href="{% url 'app3:index' %}">
                <button>Regresar</button>
            </a>
        </div>
        <br>
        <div>
            <form style="display: flex; flex-direction: row; width: 100%; justify-content: center;" method="post" action="{% url 'app3:nuevoUsuario' %}">
                {% csrf_token %}
                <div style="width: 60%;">
                    <div style="display: flex; flex-direction: row; justify-content: space-between;">
                        <div style="display: flex; flex-direction: column; width: 45%;">
                            <label>Nombre</label>
                            <input type="text" name="nombre" required>
                        </div>
                        <div style="display: flex; flex-direction: column; width: 45%;">
                            <label>Apellido</label>
                            <input type="text" name="apellido" required>
                        </div>
                    </div>
                    <div style="display: flex; flex-direction: row; justify-content: space-between;">
                        <div style="display: flex; flex-direction: column; width: 45%;">
                            <label>Fecha de nacimiento</label>
                            <input type="date" name="fecha" required>
                        </div>
                        <div style="display: flex; flex-direction: column; width: 45%;">
                        </div>
                    </div>
                    <div style="display: flex; flex-direction: row; justify-content: space-between;">
                        <div style="display: flex; flex-direction: column; width: 45%;">
                            <label>Tipo Persona</label>
                            <input type="text" name="tipo" required>
                        </div>
                        <div style="display: flex; flex-direction: column; width: 45%;">
                            <label>Codigo</label>
                            <input type="text" name="codigo" required>
                        </div>
                    </div>
                    <div style="display: flex; flex-direction: row; justify-content: space-between;">
                        <div style="display: flex; flex-direction: column; width: 45%;">
                            <label>Telefono</label>
                            <input type="text" name="telefono" required>
                        </div>
                        <div style="display: flex; flex-direction: column; width: 45%;">
                            <label>Residencia</label>
                            <input type="text" name="residencia" required>
                        </div>
                    </div>
                    <br>
                    <div>
                        <input type="submit" value="Crear usuario">
                    </div>
                </div>
            </form>
        </div>
    </body>
</html>

app3/templates/verTareas.html
<!DOCTYPE html>
<html>
    <head>
        <title>Gestor de tareas</title>
        <style>
            table {
                width: 80%;
                border-collapse: collapse;
            }

            table, th, td {
                border: 1px solid;
            }
        </style>
    </head>
    <body>
        <div style="text-align: center;">
            <h1>VISTA DE TAREAS</h1>
        </div>
        <div style="display: flex; flex-direction: row; justify-content: space-around;">
            <a href="{% url 'app3:index' %}">
                <button style="width: 120px;">Regresar</button>
            </a>
            <a>
            </a>
        </div>
        <br>
        <div style="display: flex; flex-direction: row; justify-content: center;">
            <table>
                <thead>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                </thead>
                <tbody>
                    {% for tareaInfo in tareasxUsuario %}
                    <tr>
                        <td>{{ tareaInfo.nombre }}</td>
                        <td>{{ tareaInfo.descripcion }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>
</html>