app1/urls.py
from django.urls import path
from . import views

app_name='app1'

urlpatterns = [
    path('',views.index,name='index'),
    path('rutaEjemplo',views.rutaEjemplo,name='rutaEjemplo')
]

app4/urls.py
from django.urls import path
from . import views

app_name='app4'

urlpatterns = [
    path('',views.index,name='index'),
    path('perfilUsuario',views.perfilUsuario,name='perfilUsuario'),
    path('consolaAdministrador',views.consolaAdministrador,name='consolaAdministrador'),
    path('cerrarSesion',views.cerrarSesion,name='cerrarSesion'),
    path('finalizarTarea/<str:idTarea>',views.finalizarTarea,name='finalizarTarea'),
    path('ejemploJs',views.ejemploJs,name='ejemploJs'),
    path('devolverMensaje',views.devolverMensaje,name='devolverMensaje'),
    path('conseguirInfoTarea',views.conseguirInfoTarea,name='conseguirInfoTarea'),
    path('publicarComentario',views.publicarComentario,name='publicarComentario'),
    path('react1',views.react1,name='react1'),
    path('obtenerDatosUsuario',views.obtenerDatosUsuario,name='obtenerDatosUsuario'),
    path('actualizarUsuario',views.actualizarUsuario,name='actualizarUsuario')
]

primerProyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app4.urls')),
    path('app2/',include('app2.urls')),
    path('app3/',include('app3.urls')),
    path('app1/',include('app1.urls')),
]

#127.0.0.1:8000/   app2   / welcome

app4/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User

# Create your models here.
class datosUsuario(models.Model):
    userRel = models.OneToOneField(User,on_delete=models.CASCADE)
    nroCelular = models.CharField(max_length=16, null=True, blank=True)
    profesionUsuario = models.CharField(max_length=64, null=True, blank=True)
    perfilUsuario = models.CharField(max_length=512, null=True, blank=True)
    fechaCreacion = models.DateField(default=date.today)

class tareasSistem(models.Model):
    nombreTarea = models.CharField(max_length=32, null=True, blank=True)
    descripcionTarea = models.CharField(max_length=512, null=True, blank=True)
    fechaFin = models.DateField(default=date.today)
    fechaInicio = models.DateField(default=date.today)
    estadoTarea = models.CharField(max_length=16, null=True, blank=True)
    usuarioCreador = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    usuarioResponsable = models.ForeignKey(datosUsuario, on_delete=models.SET_NULL, null=True, blank=True)

class comentarioTarea(models.Model):
    tareaRelacionada = models.ForeignKey(tareasSistem,on_delete=models.CASCADE)
    usuarioRelacionado = models.ForeignKey(User,on_delete=models.CASCADE)
    comentario = models.CharField(max_length=512, null=True, blank=True)

app4/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import datosUsuario, tareasSistem, comentarioTarea
import datetime
import json

# Create your views here.
def index(request):
    usuariosTotales = User.objects.all()
    listaObjetos = []
    for user in usuariosTotales:
        listaObjetos.append(user.first_name)
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        contraUsuario = request.POST.get('contraUsuario')
        usrObj = authenticate(request, username=nombreUsuario, password=contraUsuario)
        if usrObj is not None:
            login(request,usrObj)
            return HttpResponseRedirect(reverse('app4:perfilUsuario'))
        else:
            return HttpResponseRedirect(reverse('app4:index'))
    return render(request,'ingresoUsuario.html',{
        'mensajeBienvenida':"Hello everyone. Welcome to task management system.",
        'listaObjetos': listaObjetos
    })

@login_required(login_url='/')
def perfilUsuario(request):
    if request.method == 'POST':
        nombreTarea = request.POST.get('nombreTarea')
        responsableTarea = request.POST.get('responsableTarea')
        fechaInicio = request.POST.get('fechaInicio')
        fechaFin = request.POST.get('fechaFin')
        descripcionTarea = request.POST.get('descripcionTarea')
        print(nombreTarea)
        print(responsableTarea)
        print(fechaInicio)
        print(fechaFin)
        print(descripcionTarea)
        usrExt = datosUsuario.objects.get(id=responsableTarea)
        tareasSistem.objects.create(
            nombreTarea=nombreTarea,
            descripcionTarea=descripcionTarea,
            fechaFin=datetime.datetime.strptime(fechaFin,'%Y-%m-%d'),
            fechaInicio=datetime.datetime.strptime(fechaInicio,'%Y-%m-%d'),
            estadoTarea='IN PROGRESS',
            usuarioResponsable=usrExt,
            usuarioCreador=request.user
        )
        return HttpResponseRedirect(reverse('app4:perfilUsuario'))
    return render(request,'informacionUsuario.html',{
        'usuariosExtendidos':datosUsuario.objects.all(),
        'tareasTotales':tareasSistem.objects.all()
    })

@login_required(login_url='/')
def consolaAdministrador(request):
    if request.method == 'POST':
        usernameUsuario = request.POST.get('usernameUsuario')
        contraUsuario = request.POST.get('contraUsuario')
        nombreUsuario = request.POST.get('nombreUsuario')
        apellidoUsuario = request.POST.get('apellidoUsuario')
        profesionUsuario = request.POST.get('profesionUsuario')
        emailUsuario = request.POST.get('emailUsuario')
        nroCelular = request.POST.get('nroCelular')
        perfilUsuario = request.POST.get('perfilUsuario')
        usuarioNuevo = User.objects.create(
            username=usernameUsuario,
            email=emailUsuario
        )
        usuarioNuevo.set_password(contraUsuario)
        usuarioNuevo.first_name = nombreUsuario
        usuarioNuevo.last_name = apellidoUsuario
        usuarioNuevo.is_staff = True
        usuarioNuevo.save()
        datosUsuario.objects.create(
            userRel = usuarioNuevo,
            nroCelular = nroCelular,
            profesionUsuario = profesionUsuario,
            perfilUsuario = perfilUsuario
        )
        return HttpResponseRedirect(reverse('app4:consolaAdministrador'))
    return render(request,'consolaAdministrador.html',{
        'usuariosTotales':User.objects.all()
    })

def cerrarSesion(request):
    logout(request)
    return HttpResponseRedirect(reverse('app4:index'))

def finalizarTarea(request,idTarea):
    tareaObj = tareasSistem.objects.get(id=idTarea)
    tareaObj.estadoTarea = 'FINISHED'
    tareaObj.save()
    return HttpResponseRedirect(reverse('app4:perfilUsuario'))

def ejemploJs(request):
    return render(request,'ejemploJs.html')

def devolverMensaje(request):
    nombre = request.GET.get('nombre')
    apellido = request.GET.get('apellido')
    return JsonResponse({
        'datosRecibidos':{
            'nombre':nombre,
            'apellido':apellido,
        },
        'mensaje':'Hola desde el servidor Django'
    })

def conseguirInfoTarea(request):
    comentariosTotales = []
    idTarea = request.GET.get('idTarea')
    tareaSeleccionada = tareasSistem.objects.get(id=idTarea)
    comentariosTarea = tareaSeleccionada.comentariotarea_set.all().order_by('id')
    for comentarioInfo in comentariosTarea:
        comentariosTotales.append([
            str(comentarioInfo.usuarioRelacionado.first_name),
            comentarioInfo.comentario
        ])
    return JsonResponse({
        'idTarea':tareaSeleccionada.id,
        'nombreTarea':tareaSeleccionada.nombreTarea,
        'descripcionTarea':tareaSeleccionada.descripcionTarea,
        'estadoTarea':tareaSeleccionada.estadoTarea,
        'fechaFin':tareaSeleccionada.fechaFin.strftime("%d-%m-%Y"),
        'fechaInicio':tareaSeleccionada.fechaInicio.strftime("%d-%m-%Y"),
        'comentariosTotales':comentariosTotales
    })

def publicarComentario(request):
    datos = json.load(request)
    idTarea = datos.get('idTarea')
    comentario = datos.get('comentario')
    usuarioRelacionado = request.user
    tareaRelacionada = tareasSistem.objects.get(id=idTarea)
    comentarioTarea.objects.create(
        tareaRelacionada=tareaRelacionada,
        usuarioRelacionado=usuarioRelacionado,
        comentario=comentario
    )
    return JsonResponse({
        'resp':'ok'
    })

def react1(request):
    return render(request,'react1.html')

def obtenerDatosUsuario(request):
    idUsuario = request.GET.get('idUsuario')
    """
    Pregunta 2
    Esta funcion devolvera los campos que se necesitan 
    cargar en la ventana modal para poder ser editados
    Con el id del usuario se puede obtener el objeto y devolver
    el objeto Json con la informacion necesaria.
    """
    usuarioEditar = User.objects.get(id=idUsuario)
    usuarioExtendido = datosUsuario.objects.get(userRel=usuarioEditar)

    return JsonResponse({
        'resp':'200',
        'idUsuario': usuarioEditar.id,
        'usernameUsuario': usuarioEditar.username,
        'nombreUsuario': usuarioEditar.first_name,
        'apellidoUsuario': usuarioEditar.last_name,
        'profesionUsuario': usuarioExtendido.profesionUsuario,
        'emailUsuario': usuarioEditar.email,
        'nroCelular': usuarioExtendido.nroCelular,
        'perfilUsuario': usuarioExtendido.perfilUsuario
    })

def actualizarUsuario(request):
    """
    Pregunta 4
    En esta funcion recibira los datos del formulario de actualizacion de usuario
    Debe capturar dichos datos, recuerde que en el input con atributo name idUsuario
    se ha cargado el id del usuario correspondiente lo que le permitira obtener el objeto
    de la base de datos. Con el objeto capturado modificar los campos respectivos y finalmente
    ejecutar el metodo save() para su respectiva actualizacion
    """

    if request.method == 'POST':
        nombreUsuarioDetalle = request.POST.get('nombreUsuarioDetalle')
        apellidoUsuarioDetalle = request.POST.get('apellidoUsuarioDetalle')
        profesionUsuarioDetalle = request.POST.get('profesionUsuarioDetalle')
        nroCelularDetalle = request.POST.get('nroCelularDetalle')
        perfilUsuarioDetalle = request.POST.get('perfilUsuarioDetalle')
        idUsuario = request.POST.get('idUsuario')
        usuarioEdit = User.objects.get(id=idUsuario)
        usuarioExt = datosUsuario.objects.get(userRel=usuarioEdit)

        usuarioEdit.first_name = nombreUsuarioDetalle
        usuarioEdit.last_name = apellidoUsuarioDetalle
        usuarioEdit.save()
        usuarioExt.profesionUsuario = profesionUsuarioDetalle
        usuarioExt.nroCelular = nroCelularDetalle
        usuarioExt.perfilUsuario = perfilUsuarioDetalle
        usuarioExt.save()
    return HttpResponseRedirect(reverse('app4:consolaAdministrador'))

app4/templates/consolaAdministrador.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Administrator Console</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <!--Importar scripts de javascript-->
        <script src="{% static 'informacionUsuario.js' %}"></script>
    </head>
    <body>
        <div class="bg-primary">
            <div class="container">
                <div class="row justify-content-between align-items-center">
                    <div class="col-4 mt-3 mb-3 text-white">
                        <div class="row">
                            <h5>Welcome {{ user.first_name }} {{ user.last_name }}</h5>
                        </div>
                        <div class="row">
                            <h5>{{ user.datosusuario.profesionUsuario }}</h5>
                        </div>
                    </div>
                    <div class="col-1">
                        <a class="btn btn-success" href="{% url 'app4:cerrarSesion' %}"><i class="fa-solid fa-right-to-bracket"></i> Sign Out</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container mt-3 mb-3">
            <div>
                <a href="{% url 'app4:perfilUsuario' %}" class="btn btn-info">Back <i class="fa-solid fa-arrow-left"></i></a>
            </div>
        </div>
        <div class="mt-5 text-center">
            <h1>User Management</h1>
        </div>
        <div class="mt-5 container">
            <div class="row justify-content-between">
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevoUsuario"><i class="fa-solid fa-user-plus"></i> Add User</button>
                </div>
                <div class="col-2">
                    <a class="btn btn-success" href="#"><i class="fa-solid fa-download"></i> Download</a>
                </div>
            </div>
        </div>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered">
                        <thead class="table-dark">
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Cell number</th>
                            <th>Registration Date</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </thead>
                        <tbody>
                            {% for usuarioInfo in usuariosTotales %}
                            <tr>
                                <td>{{ usuarioInfo.first_name }}</td>
                                <td>{{ usuarioInfo.last_name }}</td>
                                <td>{{ usuarioInfo.datosusuario.nroCelular }}</td>
                                <td>{{ usuarioInfo.datosusuario.fechaCreacion }}</td>
                                <td class="text-center"><a class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#editarUsuario" id="{{ usuarioInfo.id }}" onclick="cargarInformacionUsuario(this.id)"><i class="fa-solid fa-edit"></i></a></td>
                                <td class="text-center"><a class="btn btn-danger" href="#"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

<!--Nuevo usuario-->
<div class="modal fade" id="nuevoUsuario" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="{% url 'app4:consolaAdministrador' %}">
            {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Create new user</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Username:</label>
                            <input class="form-control" type="text" name="usernameUsuario" required>
                        </div>
                        <div class="col-5">
                            <label>Password:</label>
                            <input class="form-control" type="password" name="contraUsuario" required>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>First Name:</label>
                            <input class="form-control" type="text" name="nombreUsuario" required>
                        </div>
                        <div class="col-5">
                            <label>Last Name:</label>
                            <input class="form-control" type="text" name="apellidoUsuario" required>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Occupation:</label>
                            <input class="form-control" type="text" name="profesionUsuario" required>
                        </div>
                        <div class="col-5">
                            <label>Email:</label>
                            <input class="form-control" type="email" name="emailUsuario" required>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Cell number:</label>
                            <input class="form-control" type="text" name="nroCelular" required>
                        </div>
                        <div class="col-5">
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-11">
                            <label>User Profile:</label>
                            <textarea class="form-control" type="text" name="perfilUsuario" rows="4" required></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!--
    Pregunta 1
    Completar la ventana modal con los campos requeridos para
    implementar la funcionalidad de edicion de usuarios
-->


<!--Editar usuario-->
<div class="modal fade" id="editarUsuario" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="{% url 'app4:actualizarUsuario' %}">
            {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Edit user</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div style="display: none;">
                    <input id="idUsuario" name="idUsuario" value="">
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-11">
                            <label>Username:</label>
                            <input class="form-control" type="text" id="usernameUsuarioDetalle" name="usernameUsuarioDetalle" readonly>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>First Name:</label>
                            <input class="form-control" type="text" id="nombreUsuarioDetalle" name="nombreUsuarioDetalle">
                        </div>
                        <div class="col-5">
                            <label>Last Name:</label>
                            <input class="form-control" type="text" id="apellidoUsuarioDetalle" name="apellidoUsuarioDetalle">
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Occupation:</label>
                            <input class="form-control" type="text" id="profesionUsuarioDetalle" name="profesionUsuarioDetalle">
                        </div>
                        <div class="col-5">
                            <label>Email:</label>
                            <input class="form-control" type="email" id="emailUsuarioDetalle" name="emailUsuarioDetalle" readonly>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Cell number:</label>
                            <input class="form-control" type="text" id="nroCelularDetalle" name="nroCelularDetalle">
                        </div>
                        <div class="col-5">
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-11">
                            <label>User Profile:</label>
                            <textarea class="form-control" type="text" id="perfilUsuarioDetalle" name="perfilUsuarioDetalle" rows="4"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
            </form>
        </div>
    </div>
</div>

app4/templates/ingresoUsuario.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Login View</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="bg-light position-absolute start-50 top-50 translate-middle" style="height: 700px; width: 600px;">
            <div class="bg-light position-absolute start-50 top-50 translate-middle text-center" style="width: 300px; height: 550px;">
                <h3>{{ mensajeBienvenida }}</h3>
                <h3>{{ var1 }}</h3>
                {% for elemento in listaObjetos %}
                <h3>{{ elemento }}</h3>
                {% endfor %}
                <form method="post" action="{% url 'app4:index' %}">
                {% csrf_token %}
                    <img src="{% static 'logoApp.png' %}" width="100px" class="mb-3">
                    <div class="form-group mb-3">
                        <label>
                            Enter your username:
                        </label>
                        <input class="form-control" type="text" name="nombreUsuario" placeholder="Username">
                    </div>
                    <div class="form-group mb-3">
                        <label>
                            Enter your password:
                        </label>
                        <input class="form-control" type="password" name="contraUsuario" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-primary mb-3"><i class="fa-solid fa-right-to-bracket"></i> Sign in</button>
                    <img src="{% static 'logoPUCP.png' %}" width="300px">
                </form>
            </div>
        </div>
    </body>
</html>